<?php

/**
 * This is the model base class for the table "categoria".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Categoria".
 *
 * Columns in table "categoria" available as properties of the model,
 * followed by relations of table "categoria" available as properties of the model.
 *
 * @property integer $idcategoria
 * @property string $titulo
 * @property string $ativo
 *
 * @property Novidade[] $novidades
 */
abstract class BaseCategoria extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'categoria';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Categoria|Categorias', $n);
	}

	public static function representingColumn() {
		return array('titulo');
	}

	public function rules() {
		return array(
			array('titulo', 'length', 'max'=>100),
			array('ativo', 'length', 'max'=>1),
			array('titulo, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idcategoria, titulo, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'novidades' => array(self::HAS_MANY, 'Novidade', 'categoria_idcategoria'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcategoria' => Yii::t('app', 'Idcategoria'),
			'titulo' => Yii::t('app', 'Titulo'),
			'ativo' => Yii::t('app', 'Ativo'),
			'novidades' => Yii::t('app', 'Novidade'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcategoria', $this->idcategoria);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}