<?php

/**
 * This is the model base class for the table "newsletter".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Newsletter".
 *
 * Columns in table "newsletter" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idnewsletter
 * @property string $email
 * @property string $ativo
 *
 */
abstract class BaseNewsletter extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'newsletter';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Newsletter|Newsletters', $n);
	}

	public static function representingColumn() {
		return array('email');
	}

	public function rules() {
		return array(
			array('email', 'length', 'max'=>100),
			array('ativo', 'length', 'max'=>1),
			array('email, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idnewsletter, email, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idnewsletter' => Yii::t('app', 'Idnewsletter'),
			'email' => Yii::t('app', 'Email'),
			'ativo' => Yii::t('app', 'Ativo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idnewsletter', $this->idnewsletter);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}