<?php

/**
 * This is the model base class for the table "empreendimento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Empreendimento".
 *
 * Columns in table "empreendimento" available as properties of the model,
 * followed by relations of table "empreendimento" available as properties of the model.
 *
 * @property integer $idempreendimento
 * @property integer $emp_categoria_idemp_categoria
  * @property string $titulo
 * @property string $chamada
 * @property string $capa
 * @property string $imagem
  * @property integer $gallery_id
 * @property integer $gallery_id1
 * @property string $fundacao
 * @property string $estrutura
 * @property string $vadacao
 * @property string $instalacao
 * @property string $acabamento
 * @property string $titulo_2
 * @property string $texto_2
 * @property string $suite
 * @property string $garagem
 * @property string $area_lazer
 * @property string $metragem
 * @property string $elevador
 * @property string $ap_andar
 * @property string $terreno
 * @property string $pavimentos
 * @property string $adicional_1
 * @property string $adicional_2
 * @property string $adicional_3
 * @property string $adicional_4
 * @property string $endereco
 * @property string $cidade_estado
 * @property string $mapa
 * @property string $ativo
 *
 * @property EmpCategoria $empCategoria
 * @property Gallery $gallery
 */
abstract class BaseEmpreendimento extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'empreendimento';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Empreendimento|Empreendimentos', $n);
	}

	public static function representingColumn() {
		return array('titulo');
	}

	public function rules() {
		return array(
			array('emp_categoria_idemp_categoria, gallery_id, gallery_id1', 'required'),
			array('emp_categoria_idemp_categoria, gallery_id, gallery_id1', 'numerical', 'integerOnly'=>true),
			array('fundacao, estrutura, vadacao, instalacao, acabamento, suite, garagem, area_lazer, metragem, elevador, ap_andar, terreno, pavimentos, adicional_1, adicional_2, adicional_3, adicional_4, endereco, cidade_estado', 'length', 'max'=>100),
			array('titulo', 'length', 'max'=>45),
			array('capa, imagem', 'length', 'max'=>140),
			array('titulo_2', 'length', 'max'=>200),
			array('ativo', 'length', 'max'=>1),
			array('chamada, texto_2, mapa', 'safe'),
			array('titulo, chamada, capa, imagem, fundacao, estrutura, vadacao, instalacao, acabamento, titulo_2, texto_2, suite, garagem, area_lazer, metragem, elevador, ap_andar, terreno, pavimentos, adicional_1, adicional_2, adicional_3, adicional_4, endereco, cidade_estado, mapa, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idempreendimento, emp_categoria_idemp_categoria, titulo, chamada, capa, imagem, gallery_id, gallery_id1, fundacao, estrutura, vadacao, instalacao, acabamento, titulo_2, texto_2, suite, garagem, area_lazer, metragem, elevador, ap_andar, terreno, pavimentos, adicional_1, adicional_2, adicional_3, adicional_4, endereco, cidade_estado, mapa, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'empCategoria' => array(self::BELONGS_TO, 'EmpCategoria', 'emp_categoria_idemp_categoria'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idempreendimento' => Yii::t('app', 'Idempreendimento'),
			'emp_categoria_idemp_categoria' => Yii::t('app', 'Categoria'),
			'titulo' => Yii::t('app', 'Titulo'),
			'chamada' => Yii::t('app', 'Chamada'),
			'capa' => Yii::t('app', 'Capa'),
			'imagem' => Yii::t('app', 'Imagem'),
			'gallery_id' => Yii::t('app', 'Gaaleria de fotos'),
			'gallery_id1' => Yii::t('app', 'Planta'),
			'fundacao' => Yii::t('app', 'Fundação'),
			'estrutura' => Yii::t('app', 'Estrutura'),
			'vadacao' => Yii::t('app', 'Vedação'),
			'instalacao' => Yii::t('app', 'Instalação'),
			'acabamento' => Yii::t('app', 'Acabamento'),
			'titulo_2' => Yii::t('app', 'Titulo 2'),
			'texto_2' => Yii::t('app', 'Texto 2'),
			'suite' => Yii::t('app', 'Suíte'),
			'garagem' => Yii::t('app', 'Garagem'),
			'area_lazer' => Yii::t('app', 'Área de lazer'),
			'metragem' => Yii::t('app', 'Metragem'),
			'elevador' => Yii::t('app', 'Elevador'),
			'ap_andar' => Yii::t('app', 'Ap Andar'),
			'terreno' => Yii::t('app', 'Terreno'),
			'pavimentos' => Yii::t('app', 'Pavimentos'),
			'adicional_1' => Yii::t('app', 'Adicional 1'),
			'adicional_2' => Yii::t('app', 'Adicional 2'),
			'adicional_3' => Yii::t('app', 'Adicional 3'),
			'adicional_4' => Yii::t('app', 'Adicional 4'),
			'endereco' => Yii::t('app', 'Endereço'),
			'cidade_estado' => Yii::t('app', 'Cidade/Estado'),
			'mapa' => Yii::t('app', 'Mapa'),
			'ativo' => Yii::t('app', 'Ativo'),
			'empCategoria' => Yii::t('app', 'Categoria'),
			'gallery' => Yii::t('app', 'Galeria de fotos'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idempreendimento', $this->idempreendimento);
		$criteria->compare('emp_categoria_idemp_categoria', $this->emp_categoria_idemp_categoria);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('chamada', $this->chamada, true);
		$criteria->compare('capa', $this->capa, true);
		$criteria->compare('imagem', $this->imagem, true);
		$criteria->compare('gallery_id', $this->gallery_id);
		$criteria->compare('gallery_id1', $this->gallery_id1);
		$criteria->compare('fundacao', $this->fundacao, true);
		$criteria->compare('estrutura', $this->estrutura, true);
		$criteria->compare('vadacao', $this->vadacao, true);
		$criteria->compare('instalacao', $this->instalacao, true);
		$criteria->compare('acabamento', $this->acabamento, true);
		$criteria->compare('titulo_2', $this->titulo_2, true);
		$criteria->compare('texto_2', $this->texto_2, true);
		$criteria->compare('suite', $this->suite, true);
		$criteria->compare('garagem', $this->garagem, true);
		$criteria->compare('area_lazer', $this->area_lazer, true);
		$criteria->compare('metragem', $this->metragem, true);
		$criteria->compare('elevador', $this->elevador, true);
		$criteria->compare('ap_andar', $this->ap_andar, true);
		$criteria->compare('terreno', $this->terreno, true);
		$criteria->compare('pavimentos', $this->pavimentos, true);
		$criteria->compare('adicional_1', $this->adicional_1, true);
		$criteria->compare('adicional_2', $this->adicional_2, true);
		$criteria->compare('adicional_3', $this->adicional_3, true);
		$criteria->compare('adicional_4', $this->adicional_4, true);
		$criteria->compare('endereco', $this->endereco, true);
		$criteria->compare('cidade_estado', $this->cidade_estado, true);
		$criteria->compare('mapa', $this->mapa, true);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}