<?php

/**
 * This is the model base class for the table "novidade".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Novidade".
 *
 * Columns in table "novidade" available as properties of the model,
 * followed by relations of table "novidade" available as properties of the model.
 *
 * @property integer $idnovidade
 * @property integer $categoria_idcategoria
 * @property string $titulo
 * @property string $imagem
 * @property string $banner
 * @property string $destaque
 * @property string $destaque_texto
 * @property string $destaque_imagem
 * @property string $subtitulo
 * @property string $texto
 * @property string $ativo
 *
 * @property Categoria $categoria
 */
abstract class BaseNovidade extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'novidade';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Novidades', $n);
	}

	public static function representingColumn() {
		return array('titulo');
	}

	public function rules() {
		return array(
			array('categoria_idcategoria', 'required'),
			array('categoria_idcategoria', 'numerical', 'integerOnly'=>true),
			array('titulo', 'length', 'max'=>100),
			array('imagem, banner, destaque_imagem', 'length', 'max'=>140),
			array('destaque, subtitulo', 'length', 'max'=>200),
			array('ativo', 'length', 'max'=>1),
			array('destaque_texto, texto', 'safe'),
			array('titulo, imagem, banner, destaque, destaque_texto, destaque_imagem, subtitulo, texto, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idnovidade, categoria_idcategoria, titulo, imagem, banner, destaque, destaque_texto, destaque_imagem, subtitulo, texto, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'categoria' => array(self::BELONGS_TO, 'Categoria', 'categoria_idcategoria'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idnovidade' => Yii::t('app', 'Idnovidade'),
			'categoria_idcategoria' => Yii::t('app', 'Categoria'),
			'titulo' => Yii::t('app', 'Título'),
			'imagem' => Yii::t('app', 'Imagem'),
			'banner' => Yii::t('app', 'Banner'),
			'destaque' => Yii::t('app', 'Destaque - Título'),
			'destaque_texto' => Yii::t('app', 'Destaque - Texto'),
			'destaque_imagem' => Yii::t('app', 'Destaque - Imagem'),
			'subtitulo' => Yii::t('app', 'Subtitulo'),
			'texto' => Yii::t('app', 'Texto'),
			'ativo' => Yii::t('app', 'Ativo'),
			'categoria' => Yii::t('app', 'Categoria'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idnovidade', $this->idnovidade);
		$criteria->compare('categoria_idcategoria', $this->categoria_idcategoria);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('imagem', $this->imagem, true);
		$criteria->compare('banner', $this->banner, true);
		$criteria->compare('destaque', $this->destaque, true);
		$criteria->compare('destaque_texto', $this->destaque_texto, true);
		$criteria->compare('destaque_imagem', $this->destaque_imagem, true);
		$criteria->compare('subtitulo', $this->subtitulo, true);
		$criteria->compare('texto', $this->texto, true);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}